apiVersion: batch/v1
kind: Job
metadata:
  name: jira-clone-seeding-job
spec:
  template:
    spec:
      containers:
      - name: jira-clone-seeding
        image: glocycle/jira-clone:latest
        envFrom:
          - configMapRef:
              name: jira-clone-configs
          - secretRef:
              name: postgres-db-secrets 
        env:
          - name: RUN_SEEDING
            value: "true"
          - name: IS_BATCH_MODE
            value: "true"
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DATABASE_SERVICE)/$(POSTGRES_DB)?shema=public
      restartPolicy: Never
