configs:
    clerkPublishableKey: ENC[AES256_GCM,data:MagaAhRljfSMVjqvjFv7QnQnA/zQa8s3GV5GLzxu3EbskgiHXCSLLd7xuAEgWiTE2ww=,iv:zmy6md/iEisGudfF+lvfG6aboH49gTzxSguSPQX+fEM=,tag:LejirIPca7dn48737mwCVA==,type:str]
upstash:
    token: ENC[AES256_GCM,data:mymce6AX9glf,iv:QF14Pht4j8z87MwbhvbkQ3v1jk6uQOypQzdiv+JuVFU=,tag:AQ7BCvAN2Hrro2MsiPrS4w==,type:str]
postgresql:
    auth:
        password: ENC[AES256_GCM,data:5C2NTBXy,iv:Jd9/BFr9WglJ6fhUkdJzgXl12XhbfUqwtRRkR/5FFi0=,tag:zgVsfrcqXSGqA1uhZmhyKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ezu4feuh5qfx7evh073c2f3uegg94aguw039usg0eyfpp287qqsqw32rve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeGpqc0ptU2hXeCtPOUpL
            QXA2dTRCQWhWdjNMZHlZeTczVG1haERMdWdFCmhidklWVE40MkFWMS94aGYya2M1
            SWNVOWhDTkE3aEp5b0cvVDJRc2VROUEKLS0tIFVxQWF6ZTVIWThjMWVtYk5mbVRs
            VzZXRUYwdXJTeXVuSEcwZlE1c3Y1UTQKavso5nARu9aC/nAQ0JSAPpnapaUspRBq
            SaPIrUsWKoPD9awTvW0qSQHt2DpYEh1NxQdX1gvyFW+LKft9aMxULA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T19:14:05Z"
    mac: ENC[AES256_GCM,data:n+JXVzwoXp2+0r0v9qY5h8WhfQ/IWLXX5R0kB0ttZoOthgNfMFkENuBAxDrlKNXyQW3qVRIynYkA59Vy6wHQqVXSopsrbveqqcrILD7EBqb87X2axZfMZwW5wjRhMM3D4iTUgso40baaezXYTOaWOY0VQmiSLg/aYcr6yQ9nfeY=,iv:O8b+fM3KWo2wVXdwgeL5DTWM83cm99juGejiyMrOKo8=,tag:vibQRlqsefrGK6huCEqfyQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
