port: 3000

nameOverride: ""
fullnameOverride: ""

runMigrations: false
runSeed: false

container:
  name: jira-clone
  image:
    username: cycleglorious
    registry: ghcr.io
    password: ""
    repository: cycleglorious/jira-clone
    pullPolicy: IfNotPresent
    tag: latest
    pullSecret: "jira-clone-ghcr-auth"
  resources:
    limits:
      memory: "512Mi"
      cpu: "1000m"
  port: 3000
  replicas: 2

service:
  type: ClusterIP
  port: 3000

configs:
  nextPublicClerkPublishableKey: pk_test_bHVja3ktbGFtYi03OC5jbGVyay5hY2NvdW50cy5kZXYk
  clerkPublishableKey: ""

upstash:
  port: 80
  token: ""


postgresql:
  auth:
    database: jira-clone
    username: dbuser
    password: ""
  persistence:
    size: "1Gi"

global:
  postgresql:
    service:
     ports:
      postgresql: 5433

datadog:
  apiKeyExistingSecret: datadog-secret
  apiKey: ""
  site: "datadoghq.eu"
  logs:
    enabled: true
    containerCollectAll: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
  kubelet:
    tlsVerify: false 
  processAgent:
    enabled: true
  orchestratorExplorer:
    enabled: true

controller:
  publishService:
    enabled: true