port: 3000

nameOverride: ""
fullnameOverride: ""

runMigrations: false
runSeed: false

container:
  name: jira-clone
  image:
    username: cycleglorious
    registry: ""
    password: ""
    repository: 792642165337.dkr.ecr.eu-north-1.amazonaws.com/jira-clone
    pullPolicy: IfNotPresent
    tag: 0.0.20
    pullSecret: "jira-clone-ghcr-auth"
  resources:
    limits:
      memory: "512Mi"
      cpu: "1000m"
  port: 3000
  replicas: 1

service:
  type: ClusterIP
  port: 3000

configs:
  nextPublicClerkPublishableKey: pk_test_bHVja3ktbGFtYi03OC5jbGVyay5hY2NvdW50cy5kZXYk
  clerkPublishableKey: ""
  upstashRedisRestUrl: https://sound-elf-50165.upstash.io

upstash:
  port: 80
  token: ""


postgresql:
  auth:
    database: jira-clone
    username: dbuser
    password: ""
  dbHost: ""
  dbPort: 5432

global:
  postgresql:
    service:
     ports:
      postgresql: 5432

targetSystem: "linux"
datadog:
  apiKey: ""
  site: "datadoghq.eu"
  logs:
    enabled: true
    containerCollectAll: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
  kubelet:
    tlsVerify: false 
  processAgent:
    enabled: true
    processCollection: true
  orchestratorExplorer:
    enabled: true

controller:
  publishService:
    enabled: true