apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jira-clone.fullname" . }}
data:
  UPSTASH_REDIS_REST_URL:  {{ include "jira-clone.upstash-url" . }}
  DATABASE_SERVICE: "{{ include "jira-clone.database-fullname" . }}:{{ .Values.global.postgresql.service.ports.postgresql }}"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: {{ .Values.configs.nextPublicClerkPublishableKey }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}