apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jira-clone.fullname" . }}
  labels:
    {{- include "jira-clone.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jira-clone.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.container.replicas }}
  template:
    metadata:
      labels:
        {{- include "jira-clone.selectorLabels" . | nindent 8 }}
        admission.datadoghq.com/enabled: "true"
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: public.ecr.aws/l4l1v8r7/app/jira-clone:latest
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: {{ include "jira-clone.fullname" . }}
            - secretRef:
                name: {{ include "jira-clone.fullname" . }}
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DATABASE_SERVICE)/$(POSTGRES_DB)
            - name: DD_LOGS_INJECTION
              value: "true"

