{{- if .Values.runMigrations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jira-clone.fullname" . }}-migration-job
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.container.image.pullSecret }}
      containers:
      - name: {{ .Chart.Name }}-migration
        image: {{ include "jira-clone.image" . }}
        envFrom:
          - configMapRef:
              name: {{ include "jira-clone.fullname" . }}
          - secretRef:
              name: {{ include "jira-clone.fullname" . }}
        env:
          - name: RUN_MIGRATIONS
            value: "true"
          - name: IS_BATCH_MODE
            value: "true"
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DATABASE_SERVICE)/$(POSTGRES_DB)
      restartPolicy: Never
{{- end }}