apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-clone.fullname" . }}
type: Opaque
data:
  UPSTASH_REDIS_REST_TOKEN: {{ .Values.upstash.token | b64enc | quote }}
  CLERK_SECRET_KEY: {{ .Values.configs.clerkPublishableKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datadog.apiKeyExistingSecret }}
type: Opaque
data:
  api-key: {{ .Values.datadog.apiKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "jira-clone.dockerconfigjson" . }}