apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-clone.fullname" . }}
type: Opaque
data:
  UPSTASH_REDIS_REST_TOKEN: {{ .Values.upstash.token | b64enc | quote }}
  CLERK_SECRET_KEY: {{ .Values.configs.clerkPublishableKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
