apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira-clone.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jira-clone.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.port | default .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  sessionAffinity: ClientIP
