apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "upstash.fullname" . }}
data:
  SRH_MODE: {{ .Values.serverlessRedisHttp.configs.srhMode }}
  SRH_CONNECTION_STRING: {{ include "upstash.redis.url" . }}