apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upstash.fullname" . }}
type: Opaque
data:
  SRH_TOKEN: {{ .Values.token | default .Values.serverlessRedisHttp.configs.srhToken | b64enc | quote }}

