apiVersion: v1
kind: Service
metadata:
  name: {{ include "upstash.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "upstash.labels" . | nindent 4 }}
  ports:
  - port: {{ .Values.port | default .Values.service.port }} 
    targetPort: {{ .Values.serverlessRedisHttp.port }}
    protocol: TCP
    name: http
